name       : jasper
version    : 2.0.14
release    : 11
source     :
    - https://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.14.tar.gz : 2a1f61e55afe8b4ce8115e1508c5d7cb314d56dfcc2dd323f90c072f88ccf57b
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-9055.patch
    %patch -p1 < $pkgfiles/0001-Disable-rapth.patch
    %cmake_ninja \
        -DJAS_ENABLE_AUTOMATIC_DEPENDENCIES=FALSE
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
