name       : jasper
version    : 2.0.16
release    : 12
source     :
    - https://github.com/mdadams/jasper/archive/version-2.0.16.tar.gz : f1d8b90f231184d99968f361884e2054a1714fdbbd9944ba1ae4ebdcc9bbfdb1
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-9055.patch
    %patch -p1 < $pkgfiles/0001-Disable-rapth.patch
    %cmake_ninja \
        -DJAS_ENABLE_AUTOMATIC_DEPENDENCIES=FALSE
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
