name       : jasper
version    : 2.0.12
release    : 8
source     :
    - http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.12.tar.gz : 5b24faf5ed38670d6286e45ab7516b26458d05e7929b435afe569176765f4dda
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-6850.patch
    %cmake -DALLOW_IN_SOURCE_BUILD=TRUE -DBASH_PROGRAM=TRUE .
build      : |
    %make
install    : |
    %make_install
