name       : jasper
version    : 4.0.0
release    : 15
source     :
    - https://github.com/jasper-software/jasper/archive/refs/tags/version-4.0.0.tar.gz : 977c4c2e4210f4e37313cd2232d99e73d57ab561917b3c060bcdd5e83a0a13f1
homepage   : https://ece.engr.uvic.ca/~frodo/jasper/
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Image Processing/Coding Tool Kit
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xi)
    - pkgconfig(xmu)
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-rapth.patch
    %cmake_ninja \
        -DJAS_ENABLE_AUTOMATIC_DEPENDENCIES=FALSE
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
check      : |
    %ninja_check
