name       : jasper
version    : 2.0.10
release    : 6
source     :
    - http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.10.tar.gz : 54d85428e35263642358a11c312d61cbc054170546fae780e11271df5d1502e8
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - libjpeg-turbo-devel
setup      : |
    %cmake -DALLOW_IN_SOURCE_BUILD=TRUE -DBASH_PROGRAM=TRUE .
build      : |
    %make
install    : |
    %make_install
