name       : jasper
version    : 1.900
release    : 3
source     :
    - http://www.ece.uvic.ca/~frodo/jasper/software/jasper-1.900.1.zip : 6b905a9c2aca2e275544212666eefc4eb44d95d0a57e4305457b407fe63f9494
license    : JasPer-2.0
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
setup      : |
    ./configure --prefix=/usr --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
