name       : jasper
version    : 1.900.29
release    : 5
source     :
    - http://www.ece.uvic.ca/~frodo/jasper/software/jasper-1.900.29.tar.gz : 2ae7e9d3ba189ddcd4231e7255348d3144757d5c2ff8dd853f37e0df783925c0
license    : JasPer-2.0
component  : multimedia.library
summary    : JasPer Project is a software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard.
description: |
    JasPer Project is an open-source initiative to provide a free software-based reference implementation of the codec specified in the JPEG-2000 Part-1 standard
builddeps  :
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-9560.patch
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
